# Programming Project
## Nabil Arnaoot
## Dec 3, 2020

Initial Exploration: Mobility data

In [1]:
import pandas as pd

In [2]:
# input mobility data into mobility_df

In [3]:
mobility_filepath = "data/Google Mobility - State - Daily.csv"

In [4]:
mobility_df= pd.read_csv(mobility_filepath)

In [5]:
mobility_df

,year,month,day,statefips,gps_retail_and_recreation,gps_grocery_and_pharmacy,gps_parks,gps_transit_stations,gps_workplaces,gps_residential,gps_away_from_home
0,2020,2,24,1,0.00286,-0.00714,.0557,.06,0.01290,0.00857,-0.007980
1,2020,2,24,2,0.03000,0.00714,.0629,.0314,0.01570,0.00286,-0.000578
2,2020,2,24,4,0.03140,0.00714,.0543,.04,0.00286,0.00429,-0.007510
3,2020,2,24,5,0.02000,-0.00286,.0286,.00429,0.01570,0.00143,-0.003010
4,2020,2,24,6,0.01290,0.00286,.106,.00714,0.01140,0.00143,-0.002500
...,...,...,...,...,...,...,...,...,...,...,...
14173,2020,11,27,51,-0.16900,-0.03860,.223,-.327,-0.31600,0.10400,-0.120000
14174,2020,11,27,53,-0.27600,-0.10300,.0357,-.494,-0.36700,0.13100,-0.155000
14175,2020,11,27,54,-0.14000,-0.03290,.233,-.0871,-0.25700,0.07430,-0.085700
14176,2020,11,27,55,-0.20100,-0.04290,.334,-.286,-0.28000,0.10400,-0.117000
14177,2020,11,27,56,-0.16600,-0.04710,-.0114,-.0243,-0.24300,0.07860,-0.093200

In [6]:
# input covid data into covid_df

In [7]:
covid_filepath = "data/COVID - State - Daily.csv"

In [8]:
covid_df = pd.read_csv(covid_filepath)

In [9]:
covid_df

,year,month,day,statefips,case_count,death_count,test_count,case_rate,death_rate,test_rate,new_positives_rate,new_case_rate,new_death_rate,new_test_rate,new_case_count,new_death_count,new_test_count
0,2020,1,21,1,0,0,.,0.0,0.0,.,.,.,.,.,.,.,.
1,2020,1,21,2,0,0,.,0.0,0.0,.,.,.,.,.,.,.,.
2,2020,1,21,4,0,0,.,0.0,0.0,.,.,.,.,.,.,.,.
3,2020,1,21,5,0,0,.,0.0,0.0,.,.,.,.,.,.,.,.
4,2020,1,21,6,0,0,.,0.0,0.0,.,.,.,.,.,.,.,.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16162,2020,12,2,51,242480,4113,3378990,2841.0,48.2,39587,.232,27.1,.176,236,2311,15,20179
16163,2020,12,2,53,177929,2979,2920323,2337.0,39.1,38350,1.35,31.4,.289,30.4,2389,22,2314
16164,2020,12,2,54,49905,778,1159681,2785.0,43.4,64709,.102,54.6,.662,720,979,12,12905
16165,2020,12,2,55,420930,3715,2583546,7229.0,63.8,44372,.424,69.9,.864,183,4070,50,10651
16166,2020,12,2,56,34507,230,175973,5962.0,39.7,30405,1,92.5,.37,331,535,2,1918

In [10]:
# input state name & info (lookup table from statefips) into state_id_df

In [11]:
state_filepath = "data/GeoIDs - State.csv"

In [12]:
state_id_df = pd.read_csv(state_filepath)

In [13]:
state_id_df

    statefips             statename stateabbrev  state_pop2019
0           1               Alabama          AL        4903185
1           2                Alaska          AK         731545
2           4               Arizona          AZ        7278717
3           5              Arkansas          AR        3017804
4           6            California          CA       39512223
5           8              Colorado          CO        5758736
6           9           Connecticut          CT        3565287
7          10              Delaware          DE         973764
8          11  District Of Columbia          DC         705749
9          12               Florida          FL       21477737
10         13               Georgia          GA       10617423
11         15                Hawaii          HI        1415872
12         16                 Idaho          ID        1787065
13         17              Illinois          IL       12671821
14         18               Indiana          IN        6732219
15         19                  Iowa          IA        3155070
16         20                Kansas          KS        2913314
17         21              Kentucky          KY        4467673
18         22             Louisiana          LA        4648794
19         23                 Maine          ME        1344212
20         24              Maryland          MD        6045680
21         25         Massachusetts          MA        6892503
22         26              Michigan          MI        9986857
23         27             Minnesota          MN        5639632
24         28           Mississippi          MS        2976149
25         29              Missouri          MO        6137428
26         30               Montana          MT        1068778
27         31              Nebraska          NE        1934408
28         32                Nevada          NV        3080156
29         33         New Hampshire          NH        1359711
30         34            New Jersey          NJ        8882190
31         35            New Mexico          NM        2096829
32         36              New York          NY       19453561
33         37        North Carolina          NC       10488084
34         38          North Dakota          ND         762062
35         39                  Ohio          OH       11689100
36         40              Oklahoma          OK        3956971
37         41                Oregon          OR        4217737
38         42          Pennsylvania          PA       12801989
39         44          Rhode Island          RI        1059361
40         45        South Carolina          SC        5148714
41         46          South Dakota          SD         884659
42         47             Tennessee          TN        6829174
43         48                 Texas          TX       28995881
44         49                  Utah          UT        3205958
45         50               Vermont          VT         623989
46         51              Virginia          VA        8535519
47         53            Washington          WA        7614893
48         54         West Virginia          WV        1792147
49         55             Wisconsin          WI        5822434
50         56               Wyoming          WY         578759

In [14]:
# merge mobility & covid data into merged_df

In [15]:
merged_df = pd.merge(left=covid_df, right=mobility_df, left_on=['statefips', 'year', 'month', 'day'],right_on=['statefips', 'year', 'month', 'day'])

In [16]:
merged_df

,year,month,day,statefips,case_count,death_count,test_count,case_rate,death_rate,test_rate,...,new_case_count,new_death_count,new_test_count,gps_retail_and_recreation,gps_grocery_and_pharmacy,gps_parks,gps_transit_stations,gps_workplaces,gps_residential,gps_away_from_home
0,2020,2,24,1,0,0,.,0.0000,0.0,.,...,0,0,.,0.00286,-0.00714,.0557,.06,0.01290,0.00857,-0.007980
1,2020,2,24,2,0,0,.,0.0000,0.0,.,...,0,0,.,0.03000,0.00714,.0629,.0314,0.01570,0.00286,-0.000578
2,2020,2,24,4,1,0,.,0.0137,0.0,.,...,0,0,.,0.03140,0.00714,.0543,.04,0.00286,0.00429,-0.007510
3,2020,2,24,5,0,0,.,0.0000,0.0,.,...,0,0,.,0.02000,-0.00286,.0286,.00429,0.01570,0.00143,-0.003010
4,2020,2,24,6,11,0,.,0.0278,0.0,.,...,1,0,.,0.01290,0.00286,.106,.00714,0.01140,0.00143,-0.002500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14173,2020,11,27,51,230444,4044,3294522,2700.0000,47.4,38598,...,2445,19,33933,-0.16900,-0.03860,.223,-.327,-0.31600,0.10400,-0.120000
14174,2020,11,27,53,165230,2828,2907013,2170.0000,37.1,38175,...,2568,13,7220,-0.27600,-0.10300,.0357,-.494,-0.36700,0.13100,-0.155000
14175,2020,11,27,54,45046,712,1102054,2514.0000,39.7,61494,...,938,10,15383,-0.14000,-0.03290,.233,-.0871,-0.25700,0.07430,-0.085700
14176,2020,11,27,55,399557,3444,2533226,6862.0000,59.2,43508,...,4910,48,15121,-0.20100,-0.04290,.334,-.286,-0.28000,0.10400,-0.117000
14177,2020,11,27,56,31773,215,170677,5490.0000,37.1,29490,...,663,6,1680,-0.16600,-0.04710,-.0114,-.0243,-0.24300,0.07860,-0.093200

In [17]:
# merge combined data with state name info from

In [18]:
final_df = pd.merge(left=state_id_df, right = merged_df, left_on="statefips", right_on="statefips")

In [19]:
final_df

,statefips,statename,stateabbrev,state_pop2019,year,month,day,case_count,death_count,test_count,...,new_case_count,new_death_count,new_test_count,gps_retail_and_recreation,gps_grocery_and_pharmacy,gps_parks,gps_transit_stations,gps_workplaces,gps_residential,gps_away_from_home
0,1,Alabama,AL,4903185,2020,2,24,0,0,.,...,0,0,.,0.00286,-0.00714,.0557,.06,0.01290,0.00857,-0.00798
1,1,Alabama,AL,4903185,2020,2,25,0,0,.,...,0,0,.,0.01860,0.00143,.11,.0714,0.01000,0.00571,-0.00519
2,1,Alabama,AL,4903185,2020,2,26,0,0,.,...,0,0,.,0.03570,0.00714,.111,.0814,0.00857,0.00429,-0.00359
3,1,Alabama,AL,4903185,2020,2,27,0,0,.,...,0,0,.,0.06290,0.02430,.167,.0957,0.01140,-0.00143,0.00216
4,1,Alabama,AL,4903185,2020,2,28,0,0,.,...,0,0,.,0.07570,0.03290,.179,.0971,0.01140,-0.00286,0.00354
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14173,56,Wyoming,WY,578759,2020,11,23,29431,202,161219,...,891,8,1117,-0.16700,-0.04430,.00857,.0186,-0.18300,0.06570,-0.08070
14174,56,Wyoming,WY,578759,2020,11,24,29959,202,161747,...,787,7,1372,-0.16000,-0.02860,-.0129,.0143,-0.18700,0.06570,-0.08070
14175,56,Wyoming,WY,578759,2020,11,25,30761,215,162549,...,784,9,1370,-0.13700,0.02000,-.0186,.0114,-0.21000,0.06710,-0.08230
14176,56,Wyoming,WY,578759,2020,11,26,30761,215,162549,...,656,6,893,-0.24300,-0.07000,-.0371,-.0229,-0.27300,0.08710,-0.10200
14177,56,Wyoming,WY,578759,2020,11,27,31773,215,170677,...,663,6,1680,-0.16600,-0.04710,-.0114,-.0243,-0.24300,0.07860,-0.09320

df.groupby('countryâ€™)
df.groupby('year').lifeExp.mean()
df1 = df.groupby('date')[['A','B','C']].agg(list).reset_index()

In [20]:
grouped_df = final_df.groupby(['statename','year','month'])

In [21]:
grouped_df.head()

,statefips,statename,stateabbrev,state_pop2019,year,month,day,case_count,death_count,test_count,...,new_case_count,new_death_count,new_test_count,gps_retail_and_recreation,gps_grocery_and_pharmacy,gps_parks,gps_transit_stations,gps_workplaces,gps_residential,gps_away_from_home
0,1,Alabama,AL,4903185,2020,2,24,0,0,.,...,0,0,.,0.00286,-0.00714,.0557,.06,0.01290,0.00857,-0.00798
1,1,Alabama,AL,4903185,2020,2,25,0,0,.,...,0,0,.,0.01860,0.00143,.11,.0714,0.01000,0.00571,-0.00519
2,1,Alabama,AL,4903185,2020,2,26,0,0,.,...,0,0,.,0.03570,0.00714,.111,.0814,0.00857,0.00429,-0.00359
3,1,Alabama,AL,4903185,2020,2,27,0,0,.,...,0,0,.,0.06290,0.02430,.167,.0957,0.01140,-0.00143,0.00216
4,1,Alabama,AL,4903185,2020,2,28,0,0,.,...,0,0,.,0.07570,0.03290,.179,.0971,0.01140,-0.00286,0.00354
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14151,56,Wyoming,WY,578759,2020,11,1,13723,87,130985,...,383,3,894,-0.09570,-0.00857,.266,.13,-0.15600,0.03860,-0.04480
14152,56,Wyoming,WY,578759,2020,11,2,14167,87,134018,...,384,1,1265,-0.08710,-0.00143,.3,.106,-0.15300,0.03430,-0.03970
14153,56,Wyoming,WY,578759,2020,11,3,14619,93,135336,...,402,2,1406,-0.06860,0.00286,.381,.0886,-0.15400,0.03140,-0.03700
14154,56,Wyoming,WY,578759,2020,11,4,15044,105,135761,...,414,4,1418,-0.07430,-0.00143,.386,.08,-0.15600,0.03290,-0.03860
14155,56,Wyoming,WY,578759,2020,11,5,15409,105,138213,...,415,3,1250,-0.08140,-0.00571,.383,.0743,-0.15900,0.03430,-0.04000

In [22]:
mean_df = grouped_df.mean()

In [23]:
mean_df.head()

                      statefips  state_pop2019   day    case_count  \
statename year month
Alabama   2020 2            1.0      4903185.0  26.5      0.000000
               3            1.0      4903185.0  16.0    197.709677
               4            1.0      4903185.0  15.5   4172.200000
               5            1.0      4903185.0  16.0  12001.064516
               6            1.0      4903185.0  15.5  26676.233333

                      death_count   case_rate  death_rate  \
statename year month
Alabama   2020 2         0.000000    0.000000    0.000000
               3         1.354839    4.032000    0.027639
               4       134.800000   85.100000    2.749467
               5       465.741935  244.645161    9.492258
               6       789.900000  544.033333   16.113333

                      gps_retail_and_recreation  gps_grocery_and_pharmacy  \
statename year month
Alabama   2020 2                       0.047627                  0.016672
               3                      -0.055806                  0.078284
               4                      -0.329100                 -0.066769
               5                      -0.130177                  0.050287
               6                      -0.064133                  0.046900

                      gps_workplaces  gps_residential  gps_away_from_home
statename year month
Alabama   2020 2            0.010712         0.001428           -0.000418
               3           -0.102787         0.042226           -0.049859
               4           -0.376767         0.144267           -0.176533
               5           -0.286839         0.094558           -0.110916
               6           -0.229933         0.068713           -0.078647

In [24]:
mean_df

                      statefips  state_pop2019   day    case_count  \
statename year month
Alabama   2020 2            1.0      4903185.0  26.5      0.000000
               3            1.0      4903185.0  16.0    197.709677
               4            1.0      4903185.0  15.5   4172.200000
               5            1.0      4903185.0  16.0  12001.064516
               6            1.0      4903185.0  15.5  26676.233333
...                         ...            ...   ...           ...
Wyoming   2020 7           56.0       578759.0  16.0   2063.870968
               8           56.0       578759.0  16.0   3301.806452
               9           56.0       578759.0  15.5   4668.533333
               10          56.0       578759.0  16.0   9007.677419
               11          56.0       578759.0  14.0  22243.629630

                      death_count    case_rate  death_rate  \
statename year month
Alabama   2020 2         0.000000     0.000000    0.000000
               3         1.354839     4.032000    0.027639
               4       134.800000    85.100000    2.749467
               5       465.741935   244.645161    9.492258
               6       789.900000   544.033333   16.113333
...                           ...          ...         ...
Wyoming   2020 7        22.903226   356.612903    3.958710
               8        31.967742   570.548387    5.522258
               9        45.833333   806.700000    7.921000
               10       62.129032  1556.387097   10.723226
               11      145.111111  3843.333333   25.055556

                      gps_retail_and_recreation  gps_grocery_and_pharmacy  \
statename year month
Alabama   2020 2                       0.047627                  0.016672
               3                      -0.055806                  0.078284
               4                      -0.329100                 -0.066769
               5                      -0.130177                  0.050287
               6                      -0.064133                  0.046900
...                                         ...                       ...
Wyoming   2020 7                       0.143419                  0.320968
               8                       0.128529                  0.279548
               9                       0.045290                  0.176600
               10                     -0.060179                  0.058755
               11                     -0.149167                 -0.045192

                      gps_workplaces  gps_residential  gps_away_from_home
statename year month
Alabama   2020 2            0.010712         0.001428           -0.000418
               3           -0.102787         0.042226           -0.049859
               4           -0.376767         0.144267           -0.176533
               5           -0.286839         0.094558           -0.110916
               6           -0.229933         0.068713           -0.078647
...                              ...              ...                 ...
Wyoming   2020 7           -0.207935         0.022700           -0.019881
               8           -0.199742         0.016184           -0.012423
               9           -0.177733         0.010096           -0.007991
               10          -0.156871         0.027973           -0.034924
               11          -0.179667         0.058615           -0.072674

[510 rows x 12 columns]

In [27]:
import statsmodels.formula.api as smf

In [54]:
model = smf.ols(formula = 'gps_workplaces ~ death_rate',data = mean_df)

In [55]:
results = model.fit()

In [56]:
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         gps_workplaces   R-squared:                       0.072
Model:                            OLS   Adj. R-squared:                  0.070
Method:                 Least Squares   F-statistic:                     39.60
Date:                Fri, 04 Dec 2020   Prob (F-statistic):           6.74e-10
Time:                        17:58:15   Log-Likelihood:                 342.73
No. Observations:                 510   AIC:                            -681.5
Df Residuals:                     508   BIC:                            -673.0
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -0.2257      0.007    -32.017      0.000      -0.240      -0.212
death_rate    -0.0009      0.000     -6.293      0.000      -0.001      -0.001
==============================================================================
Omnibus:                        0.731   Durbin-Watson:                   1.168
Prob(Omnibus):                  0.694   Jarque-Bera (JB):                0.542
Skew:                           0.004   Prob(JB):                        0.763
Kurtosis:                       3.159   Cond. No.                         62.1
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [25]:
# write data to .csv file

In [26]:
mean_df.to_csv('data/grouped_mobility_data.csv')