# Programming Project
## Nabil Arnaoot
## Dec 3, 2020

Data Cleaning

In [1]:
import pandas as pd

In [2]:
# input mobility data into mobility_df

In [3]:
mobility_filepath = "data/Google Mobility - State - Daily.csv"

In [4]:
mobility_df= pd.read_csv(mobility_filepath)

In [5]:
mobility_df

,year,month,day,statefips,gps_retail_and_recreation,gps_grocery_and_pharmacy,gps_parks,gps_transit_stations,gps_workplaces,gps_residential,gps_away_from_home
0,2020,2,24,1,0.00286,-0.00714,.0557,.06,0.01290,0.00857,-0.007980
1,2020,2,24,2,0.03000,0.00714,.0629,.0314,0.01570,0.00286,-0.000578
2,2020,2,24,4,0.03140,0.00714,.0543,.04,0.00286,0.00429,-0.007510
3,2020,2,24,5,0.02000,-0.00286,.0286,.00429,0.01570,0.00143,-0.003010
4,2020,2,24,6,0.01290,0.00286,.106,.00714,0.01140,0.00143,-0.002500
...,...,...,...,...,...,...,...,...,...,...,...
14173,2020,11,27,51,-0.16900,-0.03860,.223,-.327,-0.31600,0.10400,-0.120000
14174,2020,11,27,53,-0.27600,-0.10300,.0357,-.494,-0.36700,0.13100,-0.155000
14175,2020,11,27,54,-0.14000,-0.03290,.233,-.0871,-0.25700,0.07430,-0.085700
14176,2020,11,27,55,-0.20100,-0.04290,.334,-.286,-0.28000,0.10400,-0.117000
14177,2020,11,27,56,-0.16600,-0.04710,-.0114,-.0243,-0.24300,0.07860,-0.093200

In [6]:
# input covid data into covid_df

In [7]:
covid_filepath = "data/COVID - State - Daily.csv"

In [8]:
covid_df = pd.read_csv(covid_filepath)

In [9]:
covid_df

,year,month,day,statefips,case_count,death_count,test_count,case_rate,death_rate,test_rate,new_positives_rate,new_case_rate,new_death_rate,new_test_rate,new_case_count,new_death_count,new_test_count
0,2020,1,21,1,0,0,.,0.0,0.0,.,.,.,.,.,.,.,.
1,2020,1,21,2,0,0,.,0.0,0.0,.,.,.,.,.,.,.,.
2,2020,1,21,4,0,0,.,0.0,0.0,.,.,.,.,.,.,.,.
3,2020,1,21,5,0,0,.,0.0,0.0,.,.,.,.,.,.,.,.
4,2020,1,21,6,0,0,.,0.0,0.0,.,.,.,.,.,.,.,.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16162,2020,12,2,51,242480,4113,3378990,2841.0,48.2,39587,.232,27.1,.176,236,2311,15,20179
16163,2020,12,2,53,177929,2979,2920323,2337.0,39.1,38350,1.35,31.4,.289,30.4,2389,22,2314
16164,2020,12,2,54,49905,778,1159681,2785.0,43.4,64709,.102,54.6,.662,720,979,12,12905
16165,2020,12,2,55,420930,3715,2583546,7229.0,63.8,44372,.424,69.9,.864,183,4070,50,10651
16166,2020,12,2,56,34507,230,175973,5962.0,39.7,30405,1,92.5,.37,331,535,2,1918

In [10]:
# input state name & info (lookup table from statefips) into state_id_df

In [11]:
state_filepath = "data/GeoIDs - State.csv"

In [12]:
state_id_df = pd.read_csv(state_filepath)

In [13]:
state_id_df

    statefips             statename stateabbrev  state_pop2019
0           1               Alabama          AL        4903185
1           2                Alaska          AK         731545
2           4               Arizona          AZ        7278717
3           5              Arkansas          AR        3017804
4           6            California          CA       39512223
5           8              Colorado          CO        5758736
6           9           Connecticut          CT        3565287
7          10              Delaware          DE         973764
8          11  District Of Columbia          DC         705749
9          12               Florida          FL       21477737
10         13               Georgia          GA       10617423
11         15                Hawaii          HI        1415872
12         16                 Idaho          ID        1787065
13         17              Illinois          IL       12671821
14         18               Indiana          IN        6732219
15         19                  Iowa          IA        3155070
16         20                Kansas          KS        2913314
17         21              Kentucky          KY        4467673
18         22             Louisiana          LA        4648794
19         23                 Maine          ME        1344212
20         24              Maryland          MD        6045680
21         25         Massachusetts          MA        6892503
22         26              Michigan          MI        9986857
23         27             Minnesota          MN        5639632
24         28           Mississippi          MS        2976149
25         29              Missouri          MO        6137428
26         30               Montana          MT        1068778
27         31              Nebraska          NE        1934408
28         32                Nevada          NV        3080156
29         33         New Hampshire          NH        1359711
30         34            New Jersey          NJ        8882190
31         35            New Mexico          NM        2096829
32         36              New York          NY       19453561
33         37        North Carolina          NC       10488084
34         38          North Dakota          ND         762062
35         39                  Ohio          OH       11689100
36         40              Oklahoma          OK        3956971
37         41                Oregon          OR        4217737
38         42          Pennsylvania          PA       12801989
39         44          Rhode Island          RI        1059361
40         45        South Carolina          SC        5148714
41         46          South Dakota          SD         884659
42         47             Tennessee          TN        6829174
43         48                 Texas          TX       28995881
44         49                  Utah          UT        3205958
45         50               Vermont          VT         623989
46         51              Virginia          VA        8535519
47         53            Washington          WA        7614893
48         54         West Virginia          WV        1792147
49         55             Wisconsin          WI        5822434
50         56               Wyoming          WY         578759

In [14]:
# input employment data into employ_df

In [15]:
employ_filepath="data/Employment Combined - State - Daily.csv"

In [16]:
employ_df = pd.read_csv(employ_filepath)

In [17]:
# merge mobility & covid data into merged_df

In [18]:
merged_df = pd.merge(left=covid_df, right=mobility_df, left_on=['statefips', 'year', 'month', 'day'],right_on=['statefips', 'year', 'month', 'day'])

In [19]:
merged_df

,year,month,day,statefips,case_count,death_count,test_count,case_rate,death_rate,test_rate,...,new_case_count,new_death_count,new_test_count,gps_retail_and_recreation,gps_grocery_and_pharmacy,gps_parks,gps_transit_stations,gps_workplaces,gps_residential,gps_away_from_home
0,2020,2,24,1,0,0,.,0.0000,0.0,.,...,0,0,.,0.00286,-0.00714,.0557,.06,0.01290,0.00857,-0.007980
1,2020,2,24,2,0,0,.,0.0000,0.0,.,...,0,0,.,0.03000,0.00714,.0629,.0314,0.01570,0.00286,-0.000578
2,2020,2,24,4,1,0,.,0.0137,0.0,.,...,0,0,.,0.03140,0.00714,.0543,.04,0.00286,0.00429,-0.007510
3,2020,2,24,5,0,0,.,0.0000,0.0,.,...,0,0,.,0.02000,-0.00286,.0286,.00429,0.01570,0.00143,-0.003010
4,2020,2,24,6,11,0,.,0.0278,0.0,.,...,1,0,.,0.01290,0.00286,.106,.00714,0.01140,0.00143,-0.002500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14173,2020,11,27,51,230444,4044,3294522,2700.0000,47.4,38598,...,2445,19,33933,-0.16900,-0.03860,.223,-.327,-0.31600,0.10400,-0.120000
14174,2020,11,27,53,165230,2828,2907013,2170.0000,37.1,38175,...,2568,13,7220,-0.27600,-0.10300,.0357,-.494,-0.36700,0.13100,-0.155000
14175,2020,11,27,54,45046,712,1102054,2514.0000,39.7,61494,...,938,10,15383,-0.14000,-0.03290,.233,-.0871,-0.25700,0.07430,-0.085700
14176,2020,11,27,55,399557,3444,2533226,6862.0000,59.2,43508,...,4910,48,15121,-0.20100,-0.04290,.334,-.286,-0.28000,0.10400,-0.117000
14177,2020,11,27,56,31773,215,170677,5490.0000,37.1,29490,...,663,6,1680,-0.16600,-0.04710,-.0114,-.0243,-0.24300,0.07860,-0.093200

In [20]:
# merge employment data into merged_df

In [21]:
employ_df

,year,month,day,statefips,emp_combined,emp_combined_inclow,emp_combined_incmiddle,emp_combined_inchigh,emp_combined_ss40,emp_combined_ss60,emp_combined_ss65,emp_combined_ss70
0,2020,1,14,1,-0.00307,-0.000734,-0.00671,.00141,.00194,0.00258,-.00562,-.000942
1,2020,1,14,2,-0.00311,0.028800,-0.00137,-.023,.0138,0.04100,-.0451,.0226
2,2020,1,14,4,-0.00411,-0.000003,-0.00678,-.0023,-.000351,0.00169,-.0048,-.00674
3,2020,1,14,5,-0.00508,-0.007070,-0.00756,.,.00334,-0.00933,.,-.0225
4,2020,1,14,6,-0.00588,0.005750,-0.00849,-.0054,-.002,-0.00489,-.00798,-.0068
...,...,...,...,...,...,...,...,...,...,...,...,...
13306,2020,9,30,51,-0.06900,-0.172000,-0.06260,-.00554,-.0679,-0.02650,-.076,-.226
13307,2020,9,30,53,-0.04440,-0.110000,-0.06380,-.00389,-.0438,-0.01740,-.0689,-.164
13308,2020,9,30,54,-0.07940,-0.110000,-0.07110,-.0347,-.118,-0.11800,-.0764,.00688
13309,2020,9,30,55,-0.05680,-0.166000,-0.02530,.0213,-.0605,-0.01640,-.0225,-.17
13310,2020,9,30,56,0.00312,-0.012100,-0.01160,.,.0371,0.00178,-.0125,.103

In [22]:
merged_df = pd.merge(left=merged_df, right=employ_df, left_on=['statefips', 'year', 'month', 'day'],right_on=['statefips', 'year', 'month', 'day'])

In [23]:
merged_df

,year,month,day,statefips,case_count,death_count,test_count,case_rate,death_rate,test_rate,...,gps_residential,gps_away_from_home,emp_combined,emp_combined_inclow,emp_combined_incmiddle,emp_combined_inchigh,emp_combined_ss40,emp_combined_ss60,emp_combined_ss65,emp_combined_ss70
0,2020,2,24,1,0,0,.,0.0000,0.00,.,...,0.00857,-0.007980,0.00906,-0.012600,0.0191,.0219,-.000654,-0.01000,.0248,-.00967
1,2020,2,24,2,0,0,.,0.0000,0.00,.,...,0.00286,-0.000578,-0.00137,-0.105000,0.0147,.021,.102,-0.02530,-.0243,-.0523
2,2020,2,24,4,1,0,.,0.0137,0.00,.,...,0.00429,-0.007510,0.02230,0.000688,0.0270,.0358,.019,0.00874,.0219,.0361
3,2020,2,24,5,0,0,.,0.0000,0.00,.,...,0.00143,-0.003010,0.00866,-0.001760,0.0195,.,-.00244,0.02390,.,.0407
4,2020,2,24,6,11,0,.,0.0278,0.00,.,...,0.00143,-0.002500,0.02490,-0.026800,0.0324,.0308,.0112,0.01720,.0333,.0402
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11215,2020,9,30,51,148271,3208,2057645,1737.0000,37.60,24107,...,0.08710,-0.098300,-0.06900,-0.172000,-0.0626,-.00554,-.0679,-0.02650,-.076,-.226
11216,2020,9,30,53,91560,2222,1854399,1202.0000,29.20,24352,...,0.08860,-0.101000,-0.04440,-0.110000,-0.0638,-.00389,-.0438,-0.01740,-.0689,-.164
11217,2020,9,30,54,15848,350,561568,884.0000,19.50,31335,...,0.03860,-0.040400,-0.07940,-0.110000,-0.0711,-.0347,-.118,-0.11800,-.0764,.00688
11218,2020,9,30,55,129172,1338,1552370,2219.0000,23.00,26662,...,0.06000,-0.064200,-0.05680,-0.166000,-0.0253,.0213,-.0605,-0.01640,-.0225,-.17
11219,2020,9,30,56,5948,50,101160,1028.0000,8.64,17479,...,0.01710,-0.020300,0.00312,-0.012100,-0.0116,.,.0371,0.00178,-.0125,.103

In [24]:
# merge combined data with state name info from

In [25]:
combined_df = pd.merge(left=state_id_df, right = merged_df, left_on="statefips", right_on="statefips")

In [26]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11220 entries, 0 to 11219
Data columns (total 35 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   statefips                  11220 non-null  int64
 1   statename                  11220 non-null  object
 2   stateabbrev                11220 non-null  object
 3   state_pop2019              11220 non-null  int64
 4   year                       11220 non-null  int64
 5   month                      11220 non-null  int64
 6   day                        11220 non-null  int64
 7   case_count                 11220 non-null  int64
 8   death_count                11220 non-null  int64
 9   test_count                 11220 non-null  object
 10  case_rate                  11220 non-null  float64
 11  death_rate                 11220 non-null  float64
 12  test_rate                  11220 non-null  object
 13  new_positives_rate         11220 non-null  object
 14  new_case_rate              11220 non-null  object
 15  new_death_rate             11220 non-null  object
 16  new_test_rate              11220 non-null  object
 17  new_case_count             11220 non-null  object
 18  new_death_count            11220 non-null  object
 19  new_test_count             11220 non-null  object
 20  gps_retail_and_recreation  11220 non-null  float64
 21  gps_grocery_and_pharmacy   11220 non-null  float64
 22  gps_parks                  11220 non-null  object
 23  gps_transit_stations       11220 non-null  object
 24  gps_workplaces             11220 non-null  float64
 25  gps_residential            11220 non-null  float64
 26  gps_away_from_home         11220 non-null  float64
 27  emp_combined               11220 non-null  float64
 28  emp_combined_inclow        11220 non-null  float64
 29  emp_combined_incmiddle     11220 non-null  float64
 30  emp_combined_inchigh       11220 non-null  object
 31  emp_combined_ss40          11220 non-null  object
 32  emp_combined_ss60          11220 non-null  float64
 33  emp_combined_ss65          11220 non-null  object
 34  emp_combined_ss70          11220 non-null  object
dtypes: float64(11), int64(7), object(17)
memory usage: 3.1+ MB

In [27]:
summarized_df = combined_df[['statename', 'stateabbrev', 'year','month', 'day', 'case_rate','death_rate', 'emp_combined', 'emp_combined_inclow', 'emp_combined_incmiddle', 'emp_combined_inchigh','gps_retail_and_recreation', 'gps_grocery_and_pharmacy','gps_workplaces','gps_residential','gps_away_from_home']]

In [28]:
summarized_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11220 entries, 0 to 11219
Data columns (total 16 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   statename                  11220 non-null  object
 1   stateabbrev                11220 non-null  object
 2   year                       11220 non-null  int64
 3   month                      11220 non-null  int64
 4   day                        11220 non-null  int64
 5   case_rate                  11220 non-null  float64
 6   death_rate                 11220 non-null  float64
 7   emp_combined               11220 non-null  float64
 8   emp_combined_inclow        11220 non-null  float64
 9   emp_combined_incmiddle     11220 non-null  float64
 10  emp_combined_inchigh       11220 non-null  object
 11  gps_retail_and_recreation  11220 non-null  float64
 12  gps_grocery_and_pharmacy   11220 non-null  float64
 13  gps_workplaces             11220 non-null  float64
 14  gps_residential            11220 non-null  float64
 15  gps_away_from_home         11220 non-null  float64
dtypes: float64(10), int64(3), object(3)
memory usage: 1.5+ MB

In [29]:
summarized_df = summarized_df.rename({'stateabbrev':'state'}, axis='columns')

In [30]:
summarized_df

,statename,state,year,month,day,case_rate,death_rate,emp_combined,emp_combined_inclow,emp_combined_incmiddle,emp_combined_inchigh,gps_retail_and_recreation,gps_grocery_and_pharmacy,gps_workplaces,gps_residential,gps_away_from_home
0,Alabama,AL,2020,2,24,0.0,0.00,0.009060,-0.0126,0.0191,.0219,0.00286,-0.00714,0.01290,0.00857,-0.00798
1,Alabama,AL,2020,2,25,0.0,0.00,0.009510,-0.0130,0.0197,.0232,0.01860,0.00143,0.01000,0.00571,-0.00519
2,Alabama,AL,2020,2,26,0.0,0.00,0.009960,-0.0132,0.0204,.0244,0.03570,0.00714,0.00857,0.00429,-0.00359
3,Alabama,AL,2020,2,27,0.0,0.00,0.010400,-0.0135,0.0210,.0252,0.06290,0.02430,0.01140,-0.00143,0.00216
4,Alabama,AL,2020,2,28,0.0,0.00,0.010600,-0.0138,0.0216,.0258,0.07570,0.03290,0.01140,-0.00286,0.00354
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11215,Wyoming,WY,2020,9,26,944.0,8.64,0.000739,-0.0126,-0.0230,.,0.01710,0.14000,-0.15400,0.01430,-0.01440
11216,Wyoming,WY,2020,9,27,973.0,8.64,0.002090,-0.0122,-0.0201,.,0.00429,0.12900,-0.15300,0.01710,-0.02020
11217,Wyoming,WY,2020,9,28,994.0,8.64,0.002870,-0.0122,-0.0171,.,-0.00143,0.12300,-0.15000,0.01860,-0.02190
11218,Wyoming,WY,2020,9,29,1006.0,8.64,0.003190,-0.0121,-0.0143,.,-0.00429,0.12100,-0.14700,0.01860,-0.02190
11219,Wyoming,WY,2020,9,30,1028.0,8.64,0.003120,-0.0121,-0.0116,.,-0.00286,0.12600,-0.14700,0.01710,-0.02030

In [31]:
# For initial analysis, we created dummies for the categorical state value.  However, our early exploration 
# indicated that these did not have substantial impact.  
# For later versions of this work, we have commented out the code used to create the dummies. 
# We leave it here in case if becomes relevant later.

# full_df = pd.get_dummies(summarized_df, columns=["state"])
full_df = summarized_df

In [32]:
full_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11220 entries, 0 to 11219
Data columns (total 16 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   statename                  11220 non-null  object
 1   state                      11220 non-null  object
 2   year                       11220 non-null  int64
 3   month                      11220 non-null  int64
 4   day                        11220 non-null  int64
 5   case_rate                  11220 non-null  float64
 6   death_rate                 11220 non-null  float64
 7   emp_combined               11220 non-null  float64
 8   emp_combined_inclow        11220 non-null  float64
 9   emp_combined_incmiddle     11220 non-null  float64
 10  emp_combined_inchigh       11220 non-null  object
 11  gps_retail_and_recreation  11220 non-null  float64
 12  gps_grocery_and_pharmacy   11220 non-null  float64
 13  gps_workplaces             11220 non-null  float64
 14  gps_residential            11220 non-null  float64
 15  gps_away_from_home         11220 non-null  float64
dtypes: float64(10), int64(3), object(3)
memory usage: 1.5+ MB

In [33]:
full_df['emp_combined_inchigh'] = full_df['emp_combined_inchigh'].apply(lambda x: 0 if len(x) == 1 else x)

In [34]:
full_df['gps_transit_stations'] = full_df['gps_transit_stations'].astype(float)

KeyError: 'gps_transit_stations'

In [ ]:
full_df['gps_parks'] = full_df['gps_parks'].astype(float)

In [ ]:
full_df['emp_combined_inchigh'] = full_df['emp_combined_inchigh'].astype(float)

In [ ]:
grouped_df = full_df.groupby(['statename', 'year', 'month']).mean()

In [ ]:
grouped_df = grouped_df.drop('day',axis='columns')

In [ ]:
grouped_df.info()

In [ ]:
grouped_df.reset_index(inplace=True)

In [ ]:
grouped_df.head()

In [ ]:
# write data to .csv file

In [ ]:
grouped_df.to_csv('data/grouped_mobility_data.csv')